// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"FinPull/pkg/config"
	"FinPull/pkg/server"
)

// Injectors from wire.go:

// InitializeApp wires up all dependencies and returns the application.
// Wire will generate the implementation of this function.
func InitializeApp(cfg *config.Config) (*server.App, error) {
	marketStream := ProvideFinnhubStream(cfg)
	producer, err := ProvideKafkaProducer(cfg)
	if err != nil {
		return nil, err
	}
	publisher := ProvideTradePublisher(producer, cfg)
	client, err := ProvideClickHouseClient(cfg)
	if err != nil {
		return nil, err
	}
	storage := ProvideTradeStorage(client,cfg)
	metrics := ProvideMetrics()
	tradeProcessor := ProvideTradeProcessor(publisher, storage, metrics, cfg)
	tradeCollector := ProvideTradeCollector(marketStream, tradeProcessor, metrics)
	consumer, err := ProvideKafkaConsumer(cfg)
	if err != nil {
		return nil, err
	}
	kh := ProvideKafkaTicksHandler(storage, metrics, cfg)
	app := ProvideApp(cfg, tradeCollector, consumer, kh, client)
	return app, nil
}
