{
 "title": "Go",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Go concurrency per sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go allocated ram",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "go_threads{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go heap used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}